version: 0.0
os: linux
files:
  - source: /
    destination: /opt/nexus-web
permissions:
  - object: /opt/nexus-web/scripts
    pattern: "**"
    mode: 755
    type:
      - file
hooks:
   AfterInstall:
   - location: scripts/post-deployment.sh
     runas: root
