<?php

function fs_init() {
    drupal_add_library('fs', 'fs');
}

function fs_library() {
    $libraries = array();

    $libraries['fs'] = array(
        'title'   => 'FedSpending',
        'version' => '1.0.0',
        'js' => array(
            drupal_get_path('module', 'fs').'/js/FS.js' => array('weight' => 0),
            drupal_get_path('module', 'fs').'/js/Class.js' => array('weight' => 0),
            drupal_get_path('module', 'fs').'/js/util/UriHandler.js' => array('weight' => 0),
            drupal_get_path('module', 'fs').'/js/util/DateFormat.js' => array('weight' => 0),
            drupal_get_path('module', 'fs').'/js/util/StringFormat.js' => array('weight' => 0),
            drupal_get_path('module', 'fs').'/js/util/NumberFormat.js' => array('weight' => 0),

            drupal_get_path('module', 'fs').'/js/app.js' => array('weight' => 200,'scope' => 'footer', 'group' => JS_THEME)
        ),
        'dependencies' => array(
            array('system','jquery'),
            array('fs','moment'),
            array('fs','js-cookie')
        )
    );

    $libraries['moment'] = array(
        'title'   => 'Moment',
        'version' => '2.10.6',
        'js' => array(
            'sites/all/libraries/moment/moment.min.js' => array('weight' => 0),
        )
    );

    $libraries['js-cookie'] = array(
        'title'   => 'js-cookie',
        'website' => 'https://github.com/js-cookie/js-cookie',
        'version' => '2.0.3',
        'js' => array(
            'sites/all/libraries/js-cookie/js.cookie-2.0.3.min.js' => array('weight' => 0)
        )
    );

    return $libraries;
}