<?php

function fs_search_init() {
    drupal_add_library('fs_search', 'datatables');
    drupal_add_library('fs_search', 'fs_search');
}

function fs_search_block_info() {
    $blocks = array();

    $blocks['fs_search_simple_form'] = array(
        'info' => t('FedSpending Search Simple Form')
    );

    $blocks['fs_search_advanced_form'] = array(
        'info' => t('FedSpending Search Advanced Form')
    );

    $blocks['fs_search_results'] = array(
        'info' => t('FedSpending Search Results')
    );

    return $blocks;
}

function fs_search_block_view($delta = '') {
    $block = array();
    switch ($delta) {

        case 'fs_search_simple_form':
            $block['subject'] = NULL;
            $block['content'] = theme('fs_search_simple_form');
            break;

        case 'fs_search_advanced_form':
            $block['subject'] = NULL;
            $block['content'] = theme('fs_search_advanced_form');
            break;

        case 'fs_search_results':
            $block['subject'] = NULL;
            $block['content'] = theme('fs_search_results');
            break;
    }
    return $block;
}

function fs_search_theme($existing, $type, $theme, $path) {
    return array(
        'fs_search_simple_form' => array(
            'template' => 'form--simple',
            'path' => drupal_get_path('module', 'fs_search') . '/templates',
        ),
        'fs_search_advanced_form' => array(
            'template' => 'form--advanced',
            'path' => drupal_get_path('module', 'fs_search') . '/templates',
        ),
        'fs_search_results' => array(
            'template' => 'results',
            'path' => drupal_get_path('module', 'fs_search') . '/templates',
        )
    );
}

function fs_search_library() {
    $libraries = array();

    $libraries['datatables'] = array(
        'title'   => 'DataTables',
        'website' => 'http://www.datatables.net',
        'version' => '1.10.7',
        'js' => array(
            'sites/all/libraries/datatables/media/js/jquery.dataTables.js' => array('weight' => 0),
            'sites/all/libraries/datatables/plugins/integration/bootstrap/3/dataTables.bootstrap.js' => array('weight' => 0)
        ),
        'css' => array (
            'sites/all/libraries/datatables/plugins/integration/bootstrap/3/dataTables.bootstrap.css' => array('weight'=>-1)
        ),
        'dependencies' => array(
            array('system','jquery')
        )
    );

    $libraries['fs_search'] = array(
        'title'   => 'FedSpending Search',
        'version' => '1.0.0',
        'js' => array(
            drupal_get_path('module', 'fs_search').'/js/fs/FS.js' => array('weight' => 100),
            drupal_get_path('module', 'fs_search').'/js/fs/Class.js' => array('weight' => 101),
            drupal_get_path('module', 'fs_search').'/js/util/DateFormat.js' => array('weight' => 102),
            drupal_get_path('module', 'fs_search').'/js/util/StringFormat.js' => array('weight' => 103),
            drupal_get_path('module', 'fs_search').'/js/util/NumberFormat.js' => array('weight' => 104),
            drupal_get_path('module', 'fs_search').'/js/util/UriHandler.js' => array('weight' => 105),
            drupal_get_path('module', 'fs_search').'/js/app.js' => array('weight' => 106)
        ),
        'css' => array (
            drupal_get_path('module', 'fs_search').'/css/data.css' => array('weight' => 0),
        ),
        'dependencies' => array(
            array('system','jquery')
        )
    );

    return $libraries;
}