<?php


function fs_search_block_info() {
    $blocks = array();

    $blocks['fs_search_simple_form'] = array(
        'info' => t('FedSpending Search Simple Form')
    );

    $blocks['fs_search_advanced_form'] = array(
        'info' => t('FedSpending Search Advanced Form')
    );

    $blocks['fs_search_results'] = array(
        'info' => t('FedSpending Search Results')
    );

    return $blocks;
}

function fs_search_block_view($delta = '') {
    $block = array();
    switch ($delta) {

        case 'fs_search_simple_form':
            $block['subject'] = NULL;
            $block['content'] = theme('fs_search_simple_form');
            break;

        case 'fs_search_advanced_form':
            $block['subject'] = NULL;
            $block['content'] = theme('fs_search_advanced_form');
            break;

        case 'fs_search_results':
            $block['subject'] = NULL;
            $block['content'] = theme('fs_search_results');
            break;
    }
    return $block;
}

function fs_search_theme($existing, $type, $theme, $path) {
    return array(
        'fs_search_simple_form' => array(
            'template' => 'form--simple',
            'path' => drupal_get_path('module', 'fs_search') . '/templates',
        ),
        'fs_search_advanced_form' => array(
            'template' => 'form--advanced',
            'path' => drupal_get_path('module', 'fs_search') . '/templates',
        ),
        'fs_search_results' => array(
            'template' => 'results',
            'path' => drupal_get_path('module', 'fs_search') . '/templates',
        )
    );
}